name: Link Check
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          
      - name: build
        run: |
          npm install -g yarn
          yarn install
          yarn build

      - name: Cache htmltest results
        uses: actions/cache@v3
        with:
          path: tmp/.htmltest
          # key will contain hash of all md files to check if files have changed
          # when files are changed, a new key name is formed, and thus a new cache will be saved
          key: htmltest-${{ hashFiles('docs/**/*.md') }}
          # the restore key will fetch any previously saved cache even if there is no match on key
          # this allows to use cache from prev runs and update it
          restore-keys: |
            htmltest-

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml

      - name: Archive htmltest results
        uses: actions/upload-artifact@v2
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7

