name: Link Check
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          
      - name: build
        run: |
          npm install -g yarn
          yarn install
          yarn build

      - name: Cache htmltest results
        uses: actions/cache/restore@v3
        id: cache
        with:
          # restore a cache file created against the same set of markdown files if none have changed
          # (not sure this makes sense)
          key: htmltest-${{ hashFiles('docs/**/*.md') }}
          # otherwise restore the cache created last time
          restore-keys: |
            htmltest-

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml

      - name: Store cache
        uses: actions/cache/save@v3
        id: cache
        with:
          key: htmltest-${{ hashFiles('docs/**/*.md') }}

      - name: Archive htmltest results
        uses: actions/upload-artifact@v2
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7

