name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Environment
        run: |
          export PREVIEW_BRANCH_DIR=$(echo $GITHUB_HEAD_REF | sed -e 's#^refs/heads/##; s#[^0-9a-zA-Z-]#-#g')
          echo "PREVIEW_BRANCH_DIR=$PREVIEW_BRANCH_DIR" >> $GITHUB_ENV
      
      - name: build
        env:
          DOSSIER_BASE_URL: /${{ env.PREVIEW_BRANCH_DIR }}/
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_S3_BUCKET: "doc-pr-preview"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_BUCKET_ACCESS_SECRET }}
          PR_ID: ${{ PREVIEW_BRANCH_DIR }}
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
          echo "Install yarn"
          npm install -g yarn
          echo "Install dependencies"
          yarn install
          echo "Run yarn build"
          yarn run build
          echo "Copying to website folder"
          aws s3 sync ./build s3://${AWS_S3_BUCKET}/${PR_ID}/ --exact-timestamps --delete --region ${AWS_DEFAULT_REGION} $*
          echo "Cleaning up things"
          rm -rf ~/.aws


