name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: turnerlabs/s3-docusaurus-sync-action@master
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_S3_BUCKET: "doc-pr-preview"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_BUCKET_ACCESS_SECRET }}
          PROJECT_NAME: "preview"

